pipeline {
    agent any

    stages {
        stage('Check Docker') {
            steps {
                bat 'docker --version'
            }
        }
        stage('Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/Harshit1103/react-docker.git'
            }
        }

        // stage('Install Dependencies') {
        //     steps {
        //         bat 'npm install'
        //     }
        // }

        // stage('Build') {
        //     steps {
        //         bat 'npm run build'
        //     }
        // }

        stage('Docker Build') {
            steps {
                sh 'docker build -t react-container .'
            }
        }

        stage('Docker Run') {
            steps {
                sh '''
    docker stop react-container || echo "No container to stop"
    docker rm react-container || echo "No container to remove"
'''

                
                sh 'docker run -d -p 8050:80 --name react-container react-container'
            }
        }
    }
}
