pipeline {
    agent any

    stages {
        stage('Clone Code') {
            steps {
                echo 'Cloning code from GitHub...'
                
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                
            }
        }

        stage('Push to DockerHub') {
            steps {
                echo 'Pushing Docker image to DockerHub...'
                
                }
            }

        stage('Deploy Application') {
            steps {
                echo 'Deploying application...'
                
            }
        }
    }
}